version: 2

sources:
  - name: jaffle_shop
    database: devodk-dbt-raw  
    schema: jaffle_shop  
    tables:
      - name: orders
      - name: customers

  - name: stripe
    tables:
      - name: payment